In [2]:
import pandas as pd
import numpy as np


In [3]:
ship=pd.read_csv('Titanic.csv')
ship.head()

PassengerId                                               Name  Pclass  \
0            1                            Braund, Mr. Owen Harris       3   
1            2  Cumings, Mrs. John Bradley (Florence Briggs Th...       1   
2            3                             Heikkinen, Miss. Laina       3   
3            4       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1   
4            5                           Allen, Mr. William Henry       3   

      Sex   Age SibSp  Parch            Ticket     Fare Cabin Embarked  \
0    male  22.0     1      0         A/5 21171   7.2500   NaN        S   
1  female  38.0     1      0          PC 17599  71.2833   C85        C   
2  female  26.0     0      0  STON/O2. 3101282   7.9250   NaN        S   
3  female  35.0     1      0            113803  53.1000  C123        S   
4    male  35.0     0      0            373450   8.0500   NaN        S   

   Survived  
0         0  
1         1  
2         1  
3         1  
4         0

In [4]:
ship.drop(['PassengerId','Name','SibSp','Parch','Ticket','Cabin','Embarked'],axis=1,inplace=True)
ship.head()


Pclass     Sex   Age     Fare  Survived
0       3    male  22.0   7.2500         0
1       1  female  38.0  71.2833         1
2       3  female  26.0   7.9250         1
3       1  female  35.0  53.1000         1
4       3    male  35.0   8.0500         0

In [5]:
inputs=ship[['Sex','Pclass','Age','Fare']]
target=ship.Survived


In [6]:
dummies=pd.get_dummies(inputs.Sex)
dummies.head()

female  male
0       0     1
1       1     0
2       1     0
3       1     0
4       0     1

In [7]:
inputs=pd.concat([inputs,dummies],axis='columns')
inputs.head(10)

Sex  Pclass   Age     Fare  female  male
0    male       3  22.0   7.2500       0     1
1  female       1  38.0  71.2833       1     0
2  female       3  26.0   7.9250       1     0
3  female       1  35.0  53.1000       1     0
4    male       3  35.0   8.0500       0     1
5    male       3   NaN   8.4583       0     1
6    male       1  54.0  51.8625       0     1
7    male       3   2.0  21.0750       0     1
8  female       3  27.0  11.1333       1     0
9  female       2  14.0  30.0708       1     0

In [8]:
inputs.Age=inputs.Age.fillna(inputs.Age.mean())
inputs.head(10)

Sex  Pclass        Age     Fare  female  male
0    male       3  22.000000   7.2500       0     1
1  female       1  38.000000  71.2833       1     0
2  female       3  26.000000   7.9250       1     0
3  female       1  35.000000  53.1000       1     0
4    male       3  35.000000   8.0500       0     1
5    male       3  32.149888   8.4583       0     1
6    male       1  54.000000  51.8625       0     1
7    male       3   2.000000  21.0750       0     1
8  female       3  27.000000  11.1333       1     0
9  female       2  14.000000  30.0708       1     0

In [9]:
inputs=inputs.drop('Sex',axis=1)
inputs.head()

Pclass   Age     Fare  female  male
0       3  22.0   7.2500       0     1
1       1  38.0  71.2833       1     0
2       3  26.0   7.9250       1     0
3       1  35.0  53.1000       1     0
4       3  35.0   8.0500       0     1

In [10]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(inputs,target,test_size=0.3)

In [11]:
len(x_train)

623

In [12]:
len(x_test)

268

In [13]:
len(inputs)

891

In [21]:
#Entering (Pclass , Age, Fare, female, male)
model.predict([[3,22,7,1,0]])


C:\Users\Sonu\AppData\Roaming\Python\Python37\site-packages\sklearn\base.py:451: UserWarning: X does not have valid feature names, but GaussianNB was fitted with feature names
  "X does not have valid feature names, but"


array([1], dtype=int64)

# Creating navie based model


In [14]:
from sklearn.naive_bayes import GaussianNB
model=GaussianNB()

In [15]:
model.fit(x_train,y_train)

GaussianNB()

In [16]:
model.score(x_test,y_test)

0.7947761194029851

In [17]:
model.predict(x_test)

array([0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 1,
       0, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 1, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 1, 1, 1, 0, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 1, 1, 0, 1, 0,
       0, 1, 0, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0,
       0, 1, 1, 1, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 0, 1, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 0, 0, 1, 0, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0,
       0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0,
       1, 0, 0, 0], dtype=int64)

In [18]:
model.predict_proba(x_test[:10])

array([[9.27685512e-01, 7.23144877e-02],
       [1.70577448e-03, 9.98294226e-01],
       [1.25923695e-02, 9.87407630e-01],
       [9.79726736e-01, 2.02732642e-02],
       [5.02946796e-01, 4.97053204e-01],
       [2.09346198e-04, 9.99790654e-01],
       [5.74400945e-03, 9.94255991e-01],
       [5.29252099e-03, 9.94707479e-01],
       [9.29173916e-01, 7.08260844e-02],
       [5.78376528e-01, 4.21623472e-01]])

# DONE
